version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    environment:
      HOME: /root
    volumes:
      - ./data:/root:z
    network_mode: "host"
    depends_on:
      - hbbr
    restart: always

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root:z
    network_mode: "host"
    restart: always
    # always ensures the container restarts after a reboot.  With Unless-stopped the cotainer is considered gracefully stopped during a reboot and won't restart.
